#use_frameworks!

platform :ios, '9.0'
#inhibit_all_warnings!

target 'PSPhotos_Example' do
  pod 'PSPhotos/Photos', :path => '../'
  pod 'PSPhotos/AVMedia', :path => '../'

  target 'PSPhotos_Tests' do
    inherit! :search_paths

  end
end
